### ISSUE TITLE
Inhaltsseiten bearbeiten

### ISSUE THREAD

**Issue by xelax90** [xelax90/loltournament#14]
- Inhalte an das aktuelle Turnier anpassen

**Comment by lumip** [comment]
Hier sollen einfach die inhaltlichen Änderungen der Texte übertragen werden? Das sollte ich ja ohne größere Schwierigkeiten machen können, oder?

**Comment by xelax90** [comment]
Ja, so war das gedacht. Für Dateien, die nicht Bilder sind, legst du am besten in public einen neuen Ordner an.
