### ISSUE TITLE
Über das Admin-Interface registrierte Benutzer haben keine Rolle

### ISSUE THREAD

**Issue by lumip** [xelax90/loltournament#22]
Aktion:
Benutzer "Hugo der Große" über das Admin-Interface (Seite "Users", Button "Add New User") angelegt.

Was passiert:
Der Benutzer wird ohne Probleme erstellt, erhält allerdings keine Rolle "user" (und auch sonst keine).

**Comment by xelax90** [comment]
Benutzerverwaltung komplett aus Skeleton übernommen
