### ISSUE TITLE
Unterschied zwischen "Alles okay" und "Ergebnis setzen" Buttons

### ISSUE THREAD

**Issue by lumip** [xelax90/loltournament#23]
Auf der Paarungen-Adminseite gibt es für Spiele mit eingetragenem Ergebnis die Buttons "Alles okay (blockieren)" und "Ergebnis setzen und blockieren". Was ist da genau der Unterschied?
Nach meinem Verständnis sollte Ersterer das gemeldete Ergebnis übernehmen während Letzterer dem Admin noch die Möglichkeit gibt, ein anderes Ergebnis einzutragen. Ist das korrekt?

Wenn ja, dann irritiert mich die Anzeige der Ergebnisse. Was steht vor und was steht in den Klammern z.B. bei "2 - 0 ( - )"?

**Comment by xelax90** [comment]
Die Anzeige in Klammern ist das gesetzte Ergebnis. Wenn das Ergebnis der Matches passt, muss keins gesetzt werden -> alles in Ordnung
