### ISSUE TITLE
Rundenpresets funktionieren nicht wie erwartet

### ISSUE THREAD

**Issue by lumip** [xelax90/loltournament#24]
Aktion:
Auswahl je eines Presets ("Swiss", "Random", "Knockout") auf der Seite "Runden"->"Neue Runde auslosen" des Admininterfaces.

Was passiert:
- Funktioniert ordnungsgemäß für "Swiss".
- Bei Auswahl "Random" ist unter "Typ" weiterhin "Swiss" eingetragen. Andere Werte sind zum Teil anders als bei Preset "Swiss".
- Auswahl "Knockout" hat keinen Effekt.

**Comment by xelax90** [comment]
Funktioniert wohl, wie erwartet:
das dropdown wurde nur nicht aktualisiert.
knockout ist noch gar nicht implementiert.
