### ISSUE TITLE
Formular "Neue Runde auslosen" akzeptiert Datum nicht

### ISSUE THREAD

**Issue by lumip** [xelax90/loltournament#25]
Aktion:
Auf Seite "Neue Runde auslosen" im Admininterface, Preset "Swiss" angewendet. Für Rundendauer und Terminfindung je 7 Tage angegeben. Als Startdatum je "2015-09-09 11:11", "2015-09-09 00:00" und "2015-09-20 00:00" eingegeben und auf "Auslosen" geklickt.

Was passiert:
In allen Fällen Fehlermeldung: "The input does not appear to be a valid date"

**Comment by xelax90** [comment]
fixed in 731c6b57364f0bdd57148f0a73f7ea1480c966d4
