### ISSUE TITLE
Warnings bei Teams -> Spieler bearbeiten

### ISSUE THREAD

**Issue by lumip** [xelax90/loltournament#28]
Aktion:
Klick auf Button "Spieler bearbeiten" von Team PENIXL auf Seite "Teams" im Admininterface.

Was passiert:
Entsprechende Seite lädt, produziert aber eine Menge Warnings. Darunter eine Tabelle mit Ids der Spieler, allerdings ohne Angaben in den Spalten für Name, Summoner Name und EMail.

**Comment by xelax90** [comment]
Fixed.

wo auch immer das gefixt wurde...
